### ISSUE TITLE
getting fatal error when performing checkout form magento 2 for the second time with guest suer

### ISSUE THREAD

**Issue by ganeshr28** [filrak/vsf-external-checkout#1]
hello I am getting an error when trying to do checkout  for the second time with guest user it works fine when performing for the first time but for the second time it gives error 

Fatal error: Uncaught TypeError: Return value of Divante\CartSync\Service\Sync::synchronizeGuestCart() must implement interface Divante\CartSync\Service\SyncInterface, boolean returned in /var/www/html/magento24/app/code/Divante/CartSync/Service/Sync.php:146 Stack trace: #0 /var/www/html/magento24/app/code/Divante/CartSync/Controller/Cart/Sync.php(105): Divante\CartSync\Service\Sync->synchronizeGuestCart('dface673e17a45e...') #1 /var/www/html/magento24/generated/code/Divante/CartSync/Controller/Cart/Sync/Interceptor.php(24): Divante\CartSync\Controller\Cart\Sync->execute() #2 /var/www/html/magento24/vendor/magento/framework/App/Action/Action.php(107): Divante\CartSync\Controller\Cart\Sync\Interceptor->execute() #3 /var/www/html/magento24/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /var/www/html/magento24/vendor/magento/framework/Interception/Interceptor.php(138): Divante\CartSync\Controller\Cart\Sync\Interceptor->

**Comment by pkarw** [comment]
https://github.com/DivanteLtd/magento2-external-checkout/issues/7

**Comment by filrak** [comment]
Will be fixed with this API (https://github.com/filrak/vsf-external-checkout/issues/2) after [this](https://github.com/DivanteLtd/magento2-external-checkout/issues/7) blocker will be finished ;)
